"""initial_schema

Revision ID: e93ca3a97846
Revises: 
Create Date: 2026-07-01 19:34:59.256113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e93ca3a97846'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genes',
    sa.Column('gene_id', sa.Text(), nullable=False),
    sa.Column('gene_symbol', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('gene_id')
    )
    op.create_index(op.f('ix_genes_gene_symbol'), 'genes', ['gene_symbol'], unique=False)
    op.create_table('samples',
    sa.Column('sample_id', sa.Text(), nullable=False),
    sa.Column('cohort', sa.Text(), nullable=False),
    sa.Column('sample_type', sa.Text(), nullable=False),
    sa.Column('subtype', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('expression',
    sa.Column('sample_id', sa.Text(), nullable=False),
    sa.Column('gene_id', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.gene_id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'gene_id')
    )
    op.create_index('ix_expression_gene_sample', 'expression', ['gene_id', 'sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expression_gene_sample', table_name='expression')
    op.drop_table('expression')
    op.drop_table('samples')
    op.drop_index(op.f('ix_genes_gene_symbol'), table_name='genes')
    op.drop_table('genes')
    # ### end Alembic commands ###
